services:
  web:
    build: .
    image: plixa-backend-fastapi
    container_name: web
    command: uvicorn main:app --host 0.0.0.0 --port 8082 --reload
    volumes:
      - ".:/app"
    ports:
      - "8082:8082"
    depends_on:
      - database

  database:
    image: mongo
    container_name: db
    restart: always
    env_file:
      - .env